name: Deploy Nikola to GitHub Project Pages

# Grant write permissions to GITHUB_TOKEN for pushing to gh-pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install "Nikola[extras]" markdown

    - name: Install orgmode plugin
      run: |
        source .venv/bin/activate
        nikola plugin -i orgmode

    - name: Install hyde theme
      run: |
        source .venv/bin/activate
        nikola theme -i hyde

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1  

    - name: Build site
      run: |
        source .venv/bin/activate
        nikola build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages